def config(configkey):
    """Return model configuration based on the given scale."""
    configs = {
        'tt-2k': {
            'dim': 8,
            'depth': 2,
            'mlp_dim': 8,
            'n_heads': 4,
            'learning_rate': 6e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-5k': {
            'dim': 16,
            'depth': 2,
            'mlp_dim': 16,
            'n_heads': 4,
            'learning_rate': 4.5e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-9k': {
            'dim': 16,
            'depth': 3,
            'mlp_dim': 32,
            'n_heads': 4,
            'learning_rate': 3.5e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-14k': {
            'dim': 24,
            'depth': 3,
            'mlp_dim': 24,
            'n_heads': 4,
            'learning_rate': 2.2e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-26k': {
            'dim': 32,
            'depth': 3,
            'mlp_dim': 48,
            'n_heads': 4,
            'learning_rate': 1.5e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-49k': {
            'dim': 48,
            'depth': 3,
            'mlp_dim': 192,
            'n_heads': 8,
            'learning_rate': 1.2e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-141k': {
            'dim': 64,
            'depth': 4,
            'mlp_dim': 128,
            'n_heads': 8,
            'learning_rate': 8e-3,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-808k': {
            'dim': 128,
            'depth': 4,
            'mlp_dim': 512,
            'n_heads': 16,
            'learning_rate': 2e-3,
            'batch_size': 32,
            'train_steps': 15000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-3M': {
            'dim': 256,
            'depth': 4,
            'mlp_dim': 1024,
            'n_heads': 16,
            'learning_rate': 1e-3,
            'batch_size': 32,
            'train_steps': 20000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-deep': {
            'dim': 128,
            'depth': 8,
            'mlp_dim': 512,
            'n_heads': 16,
            'learning_rate': 2e-3,
            'batch_size': 32,
            'train_steps': 15000,
            'max_len': 256,
            'dropout': 0.1,
        },
        'tt-10M': {
            'dim': 512,
            'depth': 6,
            'mlp_dim': 2048,
            'n_heads': 16,
            'learning_rate': 8e-4,
            'batch_size': 32,
            'train_steps': 25000,
            'max_len': 256,
            'dropout': 0.1,
        },
    }
    
    if configkey not in configs:
        raise ValueError(f"Unknown configuration '{configkey}'. Available configurations: {list(configs.keys())}")
    
    return configs[configkey]