def config(configkey):
    """Return model configuration based on the given scale."""
    configs = {
        'tt-1k': {
            'dim': 8,
            'depth': 1,
            'mlp_dim': 32,
            'n_heads': 2,
            'learning_rate': 5.5e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-4k': {
            'dim': 16,
            'depth': 1,
            'mlp_dim': 64,
            'n_heads': 2,
            'learning_rate': 4e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-8k': {
            'dim': 16,
            'depth': 2,
            'mlp_dim': 64,
            'n_heads': 2,
            'learning_rate': 3.4e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-14k': {
            'dim': 32,
            'depth': 1,
            'mlp_dim': 128,
            'n_heads': 2,
            'learning_rate': 1.8e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-26k': {
            'dim': 32,
            'depth': 2,
            'mlp_dim': 128,
            'n_heads': 2,
            'learning_rate': 1.3e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-50k': {
            'dim': 32,
            'depth': 4,
            'mlp_dim': 128,
            'n_heads': 4,
            'learning_rate': 1.3e-2,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-150k': {
            'dim': 64,
            'depth': 4,
            'mlp_dim': 256,
            'n_heads': 4,
            'learning_rate': 7.9e-3,
            'batch_size': 32,
            'train_steps': 10000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-800k': {
            'dim': 128,
            'depth': 4,
            'mlp_dim': 512,
            'n_heads': 4,
            'learning_rate': 1.9e-3,
            'batch_size': 32,
            'train_steps': 15000,
            'max_len': 256,
            'dropout': 0.2,
        },
        'tt-3000k': {
            'dim': 256,
            'depth': 4,
            'mlp_dim': 1024,
            'n_heads': 8,
            'learning_rate': 1.3e-3,
            'batch_size': 32,
            'train_steps': 20000,
            'max_len': 256,
            'dropout': 0.2,
        },
    }
    
    if configkey not in configs:
        raise ValueError(f"Unknown configuration '{configkey}'. Available configurations: {list(configs.keys())}")
    
    return configs[configkey]